# Generated by Django 4.2.11 on 2024-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisebike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
